### ISSUE TITLE
We seek your feedback

### ISSUE THREAD

**Issue by cuketest** [cuketest/demos#1]
[CukeTest](https://www.microsoft.com/store/apps/9p9lchrp8kb8) can be downloaded from Windows Store and use for free.

Report issues of CukeTest to help us improve the product. Your suggestions is also welcome.

**Comment by reginabecker** [comment]
I created the web project for the web-samples / calculator model.
When I run the project returns an error, can you guide me please?


Cannot find module 'chromedriver'
Error: Cannot find module 'chromedriver'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.c.default._resolveFilename (C:\Program Files (x86)\LeanPro\CukeTest\resources\app.asar\out\cucumber.js:7:35301)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\regina_dna\Desktop\Projeto Cuke Test\calculator\features\support\web_driver.js:1:156)
    at Object.<anonymous> (C:\Users\regina_dna\Desktop\Projeto Cuke Test\calculator\features\support\web_driver.js:15:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\regina_dna\Desktop\Projeto Cuke Test\calculator\features\step_definitions\definitions.js:4:18)
    at Object.<anonymous> (C:\Users\regina_dna\Desktop\Projeto Cuke Test\calculator\features\step_definitions\definitions.js:42:3)

**Comment by cuketest** [comment]
You are supposed to run "npm install" before running, which will install the packages configured in package.json, and it includes the chromedriver. please check if it is installed. Here [help document](http://cuketest.com/en/codes/packages) contains some descriptions.

**Comment by reginabecker** [comment]
Good afternoon.

Thank you so much for the feedback I was able to execute successfully.

Please, some information, is there any functionality that allows the URL to be macrosed and that map the elements of the screen to be used in Step_Definitions !?

Thankful

**Comment by cuketest** [comment]
Good to hear it can work. Not sure I understand your second question, as it related to how to selenium works, I think you can read the selenium document below to find some answer.

[http://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/](http://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/)
